version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    build: ./nginx
    container_name: devsecops-nginx
    ports:
      - "80:80"
    depends_on:
      - static-app
      - stripe-app
      - ecommerce-app
    networks:
      - devsecops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx_status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application 1: Application Statique (HTML/CSS/JS) - EXIGENCE ÉNONCÉ
  static-app:
    build: ./static-app
    container_name: devsecops-static
    networks:
      - devsecops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application 2: Application Stripe (Flask) - EXIGENCE ÉNONCÉ
  stripe-app:
    build: ./stripe-app
    container_name: devsecops-stripe
    environment:
      - STRIPE_PUBLISHABLE_KEY=pk_test_51234567890abcdef
      - STRIPE_SECRET_KEY=sk_test_51234567890abcdef
    networks:
      - devsecops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application 3: Application E-commerce Django (Rocket eCommerce) - VIA NGINX
  ecommerce-app:
    build: ./ecommerce-app
    container_name: devsecops-ecommerce
    environment:
      - DEBUG=False
      - SECRET_KEY=django-secret-key-for-production
      - STRIPE_PUBLISHABLE_KEY=pk_test_51234567890abcdef
      - STRIPE_SECRET_KEY=sk_test_51234567890abcdef
      - DATABASE_URL=sqlite:///db.sqlite3
    networks:
      - devsecops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application 4: Application PHP (ACCÈS DIRECT pour PENTESTS) - EXIGENCE ÉNONCÉ
  php-app:
    build: ./php-app
    container_name: devsecops-php
    ports:
      - "8001:8000"  # Accès direct pour les pentests (pas de reverse proxy)
    environment:
      - PHP_CLI_SERVER_WORKERS=4
    networks:
      - devsecops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  devsecops-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Volumes pour la persistance des données
volumes:
  nginx-logs:
    driver: local
  ecommerce-db:
    driver: local

