# Utilisation d'une image Nginx légère basée sur Alpine
FROM nginx:alpine

# Copie des fichiers statiques dans le répertoire de Nginx
COPY index.html /usr/share/nginx/html/

# Exposition du port 80
EXPOSE 80

# Nginx démarre automatiquement avec l'image de base

